# Generated by Django 3.1.2 on 2020-11-01 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('units_of_measurement', models.CharField(choices=[('шт', 'шт'), ('г', 'г'), ('ст.л', 'ст.л'), ('ч.л', 'ч.л'), ('мл', 'мл')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientIncomposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('slug', models.SlugField(default='', max_length=15, unique=True)),
                ('style', models.CharField(default='purple', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='irecipes/%d_%m_%Y/')),
                ('description', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('time', models.PositiveSmallIntegerField(default=10)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ingredient_in', models.ManyToManyField(to='v1.IngredientIncomposition')),
                ('tags', models.ManyToManyField(to='v1.Tags')),
            ],
        ),
    ]
