# Generated by Django 3.1.2 on 2020-12-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_favorites_shoppinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='slug',
        ),
    ]
