# Generated by Django 3.1.2 on 2020-12-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_remove_recipes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
