# Generated by Django 3.1.2 on 2020-12-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20201208_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='units_of_measurement',
        ),
    ]
