# Generated by Django 3.1.2 on 2020-12-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_remove_ingredient_units_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='units_of_measurement',
            field=models.CharField(choices=[('шт', 'шт'), ('г', 'г'), ('ст.л', 'ст.л'), ('ч.л', 'ч.л'), ('мл', 'мл')], default=12, max_length=20),
            preserve_default=False,
        ),
    ]
