# Generated by Django 3.1.2 on 2020-12-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_ingredient_units_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientincomposition',
            name='recipe',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='v1.recipes'),
            preserve_default=False,
        ),
    ]
