# Generated by Django 3.1.2 on 2020-12-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_ingredientincomposition_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientincomposition',
            name='quantity',
            field=models.SmallIntegerField(max_length=10),
        ),
    ]
