# Generated by Django 3.1.2 on 2020-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_auto_20201209_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tag',
            field=models.ManyToManyField(to='v1.Tag'),
        ),
        migrations.AlterField(
            model_name='ingredientincomposition',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
