# Generated by Django 3.1.2 on 2020-12-14 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0012_auto_20201214_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units_of_measurement',
            field=models.CharField(choices=[('шт', 'шт'), ('г', 'г'), ('ст.л', 'ст.л'), ('ч.л', 'ч.л'), ('мл', 'мл')], max_length=20, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='ingredientincomposition',
            name='quantity',
            field=models.SmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание '),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='time',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='style',
            field=models.CharField(default='purple', max_length=15, verbose_name='Цвет оформления'),
        ),
    ]
