# Generated by Django 3.1.2 on 2020-12-14 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_auto_20201214_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientincomposition',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='v1.recipes'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name='slug'),
        ),
    ]
