# Generated by Django 3.1.2 on 2020-12-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_auto_20201214_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientincomposition',
            name='recipe',
        ),
    ]
