version: "3.8"

volumes:
  postgres_data:
  static_valume:
  media_valume:

services:
  db:
    image: postgres:postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: nikminiakink/foodgram:v29
    restart: always
    command: gunicorn the_end.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_valume:/code/staticfiles
      - media_valume:/code/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    restart: always
    image: library/nginx:1.18
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_valume:/staticfiles
      - media_valume:/media
    depends_on:
      - web